# Generated by Django 5.0.3 on 2024-04-18 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slide_quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
            ],
        ),
    ]
